# Site settings
assets:
  compression: false 
  compress:
    css: sass
    js: uglifier
  sources:
    - _assets/stylesheets
    - _assets/javascripts
  precompile: [header.jpg]

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-assets
